# Generated by Django 5.0.1 on 2024-01-19 11:18

import django.db.models.deletion
import django_ckeditor_5.fields
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0004_product_alter_user_image_productimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog2',
            fields=[
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('image', models.ImageField(default='blog/default.png', upload_to='blog/image/')),
                ('text', django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps.category')),
                ('tags', models.ManyToManyField(to='apps.tag')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
