# Generated by Django 5.0.1 on 2024-01-24 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0006_email_delete_blog2'),
    ]

    operations = [
        migrations.CreateModel(
            name='CeleryTaskResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.CharField(max_length=255, unique=True)),
                ('result', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
